- name: Include alpine dependant
  import_tasks: alpine.yml
  when: ansible_facts['os_family'] == 'Alpine'
- name: Include Ubuntu od Debian dependant
  import_tasks: ubuntu.yml
  when: ansible_facts['os_family'] == 'Ubuntu' or ansible_facts['os_family'] == 'Debian'